#!/bin/sh
# Managed by npm run hooks:install.
set -eu

printf '%s\n' 'Running site checks before push...'

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    cmd.exe //d //s //c "npm.cmd test"
    ;;
  *)
    npm test
    ;;
esac
